### ISSUE TITLE
Incorrect display of the serial chart and pie chart

### ISSUE THREAD

**Issue by NikitaShchienko** [cuba-platform/charts#96]
### Environment

- Platform version: 7.2 

### Description of the bug or enhancement

Serial chart not showing for sql query with entity of list parameter.

Entity:

```
@Table(name = "TEST_PRODUCT")
@Entity(name = "test_Product")
public class Product extends StandardEntity {
    private static final long serialVersionUID = -6000426574155447300L;

    @Temporal(TemporalType.DATE)
    @Column(name = "DATE_SALE")
    protected Date dateSale;

    @Column(name = "AMOUNT")
    protected Integer amount;

...

}
```

SQL: 
```
select e.amount as "amount", e.date_sale as "dateSale" 
from test_Product e 
where e.id in ${products}
order by e.date_sale
```
Template:

![image](https://user-images.githubusercontent.com/47520144/80344950-6ed38e00-8879-11ea-9c9e-62b4fd7033e9.png)

Report:

![image](https://user-images.githubusercontent.com/47520144/80345119-b35f2980-8879-11ea-8c3e-fb007c8d7836.png)

**Additional problem 1:**

Data format not applicable for charts.
SQL:
```
select
e.amount as "amount",
e.date_sale as "dateSale"
from test_Product e 
where e.id in ${products}
order by e.date_sale
```
Formatter:

![image](https://user-images.githubusercontent.com/47520144/80344322-6e86c300-8878-11ea-94d7-098d69127e5d.png)

Report:

![image](https://user-images.githubusercontent.com/47520144/80345974-14d3c800-887b-11ea-84f8-c2dec7a4b75b.png)

**Additional problem 2:**

Incorrect data order in pie chart.

SQL: 
```
select
e.amount as "amount",
e.date_sale as "dateSale"
from test_Product e 
order by e.date_sale
```
Template:
![image](https://user-images.githubusercontent.com/47520144/80345824-d0e0c300-887a-11ea-99ce-0b6947b1421e.png)

Report:
![image](https://user-images.githubusercontent.com/47520144/80345672-89f2cd80-887a-11ea-800a-821d369f4c6c.png)

**Comment by glebfox** [comment]
Hi @NikitaShchienko.

Unfortunately, I can't reproduce the first case. Works perfectly for me:
<img width="1415" alt="Screenshot 2020-05-07 at 16 38 24" src="https://user-images.githubusercontent.com/6077149/81296360-d0b6a380-9082-11ea-96c4-131a1a04d336.png">
 
> Incorrect data order in pie chart.

Even your screenshot displays that the order is correct. Could you please elaborate on what is wrong?

Regarding the formatter problem. Serial **Chats** itself perfectly supports the `dateFormats` settings of the `categoryAxis` element. Pay attention that it's not a single value but an array for different periods like Day, Month, etc. See related docs: https://docs.amcharts.com/3/javascriptstockchart/CategoryAxis#dateFormats

In case of Pie chart, you use dates as titles, i.e. date values are sent as text and treated as text (that is correct since they are used as titles). So, the `dataProvider` configuration, in this case, looks as follows:

```
{
...
  "dataProvider": [
    {
      "dateSale": "May 7, 2020",
      "amount": 1
    },
    {
      "dateSale": "May 8, 2020",
      "amount": 2
    },
    {
      "dateSale": "May 9, 2020",
      "amount": 3
    }
  ]
}
```

This means that date values must be formatted to the correct text representation before they are sent to the client-side since Pie chart itself can't format text.

So, it appears that the problem in the Reports addon that doesn't correctly convert the formatter settings to the correct chart configuration.
